import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const callTrigger = async () => {
  const response = await fetch("https://eoa7s7zs368tk3j.m.pipedream.net/", {
    headers: {
      "Content-Type": "application/json",
    },
    method: "POST",
    body: JSON.stringify({
      tyson: "hichman",
    }),
    mode: "cors",
  });
  const data = await response.json();
  console.log(data);
};

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.content}>
          <h1>Events</h1>
          <button onClick={async () => await callTrigger()}>
            Trigger pipedream job
          </button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}